# Site/SEO settings
email: 21ways@dergigi.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics:

name: Gigi
title: 21-ways.com
description: >
  21 Ways To Look At Bitcoin
url: https://21-ways.com
twitter_username: dergigi
default_img: /assets/images/avatar.jpg
social:
  - name: twitter
    url: https://twitter.com/dergigi
  - name: mastodon
    url: https://bitcoinhackers.org/@dergigi
  - name: github
    url: https://github.com/21-ways/21-ways.github.io
  - name: bitcoin
    url: https://dergigi.com/support
  - name: patreon
    url: https://www.patreon.com/dergigi

# Collections
collections_dir: collections
collections:
  ways:
    output: true
    permalink: /:path/ # path = filename relative

# Author settings
author:
  - name: Gigi
    bio: Bio as in biological?
    url: https://dergigi.com/contact

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - env
  - scripts
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
